name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]

# Add permissions for GitHub Pages deployment
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Changed from '^24.9.0' - Node 24 doesn't exist yet
          cache: 'npm'  # Cache npm dependencies for faster builds
      
      - name: Install dependencies
        run: npm ci  # Use 'npm ci' instead of 'npm install' for CI environments
      
      - name: Build
        run: npm run build
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4  # Updated to v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Use built-in token
          publish_dir: ./build
          # Optional: Add these if needed
          # publish_branch: gh-pages
          # force_orphan: true
